language: node_js

node_js:
  - 14.5.0

before_script:
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build

script:
  - npm run test:coverage -- --maxWorkers=4

after_script:
  - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT

before_install:
  - export CHROME_BIN=chromium-browser
  - export DISPLAY=:99.0

services:
  - xvfb

notifications:
  email:
    on_failure: change

cache:
  yarn: true
  directories:
    - node_modules